<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../../src/ArchSift.Contracts/ArchSift.Contracts.csproj" />
    <ProjectReference Include="../../src/ArchSift.Core/ArchSift.Core.csproj" />
    <ProjectReference Include="../../src/ArchSift.ArchUnit/ArchSift.ArchUnit.csproj" />
    <ProjectReference Include="../../src/ArchSift.Cli/ArchSift.Cli.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="../../src/ArchSift.Web/ArchSift.Web.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
